### ISSUE TITLE
just don't work

### ISSUE THREAD

**Issue by mzjlswatt** [lazcad/homeassistant#14]
hi,lazard,hereblow is the home-assistant.log,i did it step by step,nothing missed i think ,but it still do't 
work,,can u help me out of this ,really appreciate....

17-01-22 09:51:47 homeassistant.bootstrap: Error during setup of component xiaomi
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/bootstrap.py", line 151, in _async_setup_component
    None, component.setup, hass, config)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi.py", line 59, in setup
    if comp.listen() is True:
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi.py", line 153, in listen
    self._mcastsocket = self._create_mcast_socket()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi.py", line 144, in _create_mcast_socket
    sock.bind((self.MULTICAST_ADDRESS, self.MULTICAST_PORT))
OSError: [Errno 98] Address already in use
17-01-22 10:52:22 homeassistant.core: Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 582, in _read_ready
    data = self._sock.recv(self.max_size)
OSError: [Errno 113] No route to host

**Comment by corbinmunce** [comment]
do you have something else listening on port 9898 already? -
`sock.bind((self.MULTICAST_ADDRESS, self.MULTICAST_PORT))
OSError: [Errno 98] Address already in use`

**Comment by tam-wh** [comment]
Yeah. Probably you're running aqara homebridge or something that has to do with xiaomi gateway

**Comment by mzjlswatt** [comment]
@ravetam yes, removed the aqare homebrige ,it back to work again,but the motion sensor and door sensor  
didn't work now....homekit can add it ...

**Comment by mzjlswatt** [comment]
@corbinmunce the aqara homebridge listening on port 9898 i think...really thanku for your reply

**Comment by tam-wh** [comment]
You should use homebridge HomeAssistant to connect HA to homebridge
