### ISSUE TITLE
homeassistant -> homebridge

### ISSUE THREAD

**Issue by aferraz** [lazcad/homeassistant#2]
Hi,
 firstly thanks for your wonderful work. 
In addition to homeassistant I use homebridge with a plugin that take all sensors and data from homeassistant. I wanted to notify you that the motion sensors are not visible in homebridge.
From the homebridge-homeassistant plugin readme file I notice this:
**_Binary Sensors must have a `sensor_class` set. Accepted `sensor_class`es are `moisture`, `motion`, `occupancy`, `opening` and `smoke`._**

This could be the problem ?

Regards
 Alessandro

**Comment by crisone** [comment]
what's the version number of your homebridge program?

**Comment by tam-wh** [comment]
This is fixed now with the latest commit

**Comment by aferraz** [comment]
Hi,
 I have update but get this error:
17-01-16 16:12:16 homeassistant.bootstrap: Setting up xiaomi
17-01-16 16:12:16 custom_components.xiaomi: Discovering Xiaomi Gateways
17-01-16 16:12:16 custom_components.xiaomi: Xiaomi Gateway f0b4299ac367 found at IP 192.168.1.18
17-01-16 16:12:16 custom_components.xiaomi: Discovering Xiaomi Devices
17-01-16 16:12:16 custom_components.xiaomi: Found 20 devices
17-01-16 16:12:16 homeassistant.bootstrap: Error during setup of component xiaomi
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/homeassistant/bootstrap.py", line 151, in _async_setup_component
    None, component.setup, hass, config)
  File "/usr/lib64/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homeassistant/custom_components/xiaomi.py", line 53, in setup
    comp.discoverGateways()
  File "/opt/homeassistant/custom_components/xiaomi.py", line 128, in discoverGateways
    gateway = XiaomiGateway(resp["ip"], resp["port"], resp["sid"], gatewayKey, self._socket)
  File "/opt/homeassistant/custom_components/xiaomi.py", line 225, in __init__
    self._discover_devices()
  File "/opt/homeassistant/custom_components/xiaomi.py", line 245, in _discover_devices
    model = resp["model"]
KeyError: 'model'

**Comment by aferraz** [comment]
Thanks

**Comment by aferraz** [comment]
Hi,
 the problem is present again. I don't see motion sensors in iOS Home app

Regards
 Alessandro
