### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split

### ISSUE THREAD

**Issue by rex993** [lazcad/homeassistant#28]
HA running on Ubuntu Server LTS 16.04

HA verified to work with clean install, history functionality works fine.

when starting HA with xiaomi component i have the follow error:

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/recorder/__init__.py", line 238, in run
    domain = split_entity_id(entity_id)[0]
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/core.py", line 66, in split_entity_id
    return entity_id.split(".", 1)
AttributeError: 'NoneType' object has no attribute 'split
```

when viewing history, there is no history. Current status is shown and updated correctly.

I've tried HA direct install, docker install and also virtualenv install. All have this issue. 

I've deleted configuration.yaml and HA generated a new file. I've then added:

xiaomi:
  gateways:
    - sid:
      key: 96dkmix6oxxxxxx

so it is a clean file. Still no luck. Deleting the home-assistant_v2.db file does not help either.

Rolling back to commit f8a47b15eb072e58d5c8347c6fa377ef2acf46f6 resolves this issue.

**Comment by tam-wh** [comment]
Can't reproduce this even after i enabled Recorder. The only thing that's different from your setup is that i'm using Python 3.4. 

Also, i check the next commit after f8a47b1 and there isn't any change that i can see which can cause this bug. Can you try out and let me know which commit starts producing this error?

**Comment by martonperei** [comment]
I'm getting the same error; entity_id is None in _async_delay_fire_motion in components/binary_sensor/xiaomi.py:110 when starting up.
Adding a check there works, but I can't find where it's assigned.

**Comment by rex993** [comment]
just tested all the commits. commit 497e1a7 is where the error start appearing.

**Comment by tam-wh** [comment]
Great, that will help with figuring out the issue

**Comment by Danielhiversen** [comment]
@rexii2300 @mindigmarton :
Could you try this fix:
https://github.com/Danielhiversen/homeassistant/pull/4/files

**Comment by martonperei** [comment]
Yeah, that works, been using that, though it feels like a temporary patch. I think it shouldn't reach that part of the code without an entity id, but I don't know the code enough to see if that's the case.
