### ISSUE TITLE
Motion sensor cause logbook stop working

### ISSUE THREAD

**Issue by cnberg** [lazcad/homeassistant#51]
Sometimes( I cannot finger out the certainly step), some error log occurred, as below. Then the logbook stop working anymore.

```
17-04-23 14:31:10 DEBUG (MainThread) [custom_components.xiaomi] >> b'{ "cmd":"read","sid":"158d00014dd740"}'
17-04-23 14:31:11 DEBUG (MainThread) [custom_components.xiaomi] << {'cmd': 'read_ack', 'model': 'motion', 'sid': '158d00014dd740', 'short_id': 41831, 'data': '{"voltage":3065,"status":"motion"}'}
17-04-23 14:31:11 DEBUG (MainThread) [custom_components.xiaomi] PUSH >> <Entity Motion Sensor_158d00014dd740: on>: {'voltage': 3065, 'status': 'motion'}
Exception in thread Recorder:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/recorder/__init__.py", line 251, in run
    domain = split_entity_id(entity_id)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/core.py", line 61, in split_entity_id
    return entity_id.split(".", 1)
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by Danielhiversen** [comment]
Fixed here: https://github.com/Danielhiversen/homeassistant/pull/4/files

**Comment by cnberg** [comment]
Great! It works!
Thanks.
